pinned node version

diff --git a/borger b/borger
--- a/borger
+++ b/borger
@@ -2,12 +2,19 @@
 set -euo pipefail
 echo 🍔
 
+
 IDE_CONFIG_SOURCES=(".vscode/launch.json.example" ".vscode/settings.json.example")
 IDE_CONFIG_TARGETS=(".vscode/launch.json"         ".vscode/settings.json")
 YES_RE="^([yY][eE][sS]|[yY])$"
 
-check_for_update()
+pre_launch_checks()
 {
+	if pgrep -f "RUN-CODEGEN" >/dev/null 2>&1; then
+		echo "ERROR: Please close borger dev to avoid accidentally triggering concurrent builds."
+		exit 1
+	fi
+	
+	#check for updates
 	local current_script
 	current_script="$(cat "$0")"
 
@@ -15,17 +22,24 @@ check_for_update()
 	remote_script="$(curl -fsSL --max-time 3 "https://raw.githubusercontent.com/BorgerLand/CLI/refs/heads/main/borger" 2>/dev/null)" || true
 
 	if [[ -n "$remote_script" && "$current_script" != "$remote_script" ]]; then
-		echo "Update is available for Borger CLI. You can install with:"
-		echo "  curl -fsSL https://eat.borger.dev | bash"
+		echo -e "\033[1mUpdate is available for Borger CLI. You can install with:\033[0m"
+		echo -e "\033[1m  curl -fsSL https://eat.borger.dev | bash\033[0m"
+		echo
 	fi
-}
-
-assert_dev_not_running()
-{
-	#match our own concurrently invocation from cmd_dev
-	if pgrep -f "RUN-CODEGEN" >/dev/null 2>&1; then
-		echo "ERROR: Please close borger dev to avoid accidentally triggering concurrent builds."
-		exit 1
+	
+	#use pinned node version
+	NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
+	\. "$NVM_DIR/nvm.sh"
+	
+	if ! nvm use; then
+		nvm install
+	fi
+	
+	if [[ -n "$remote_script" ]]; then
+		node_major="$(node -v)";
+		node_major="${node_major#v}";
+		node_major="${node_major%%.*}"
+		npm install --save-dev "@types/node@${node_major}"
 	fi
 }
 
@@ -37,8 +51,7 @@ cmd_init()
 		exit 1
 	fi
 	
-	assert_dev_not_running
-	check_for_update
+	pre_launch_checks
 	
 	set -x
 	local DIR="$1"
@@ -62,8 +75,7 @@ cmd_init()
 
 cmd_setup()
 {
-	assert_dev_not_running
-	check_for_update
+	pre_launch_checks
 	
 	set -x
 	
@@ -104,8 +116,7 @@ dev_help()
 
 cmd_dev()
 {
-	assert_dev_not_running
-	check_for_update
+	pre_launch_checks
 	
 	local CLIENT_FEATURES="client"
 	local VITE_HOST=""
@@ -166,7 +177,7 @@ cmd_dev()
 
 cmd_release()
 {
-	assert_dev_not_running
+	pre_launch_checks
 	check_for_update
 
 	if [ -d "release" ] || [ -d "borger/client/rs/pkg" ]; then
@@ -203,7 +214,7 @@ cmd_release()
 
 cmd_clean()
 {
-	assert_dev_not_running
+	pre_launch_checks
 	
 	#for whatever reason, git clean -X (delete gitignored files) and -e (exclude) can't
 	#be used together, so excluded files must be manually filtered from the dry run
